site:
  title: Hazelcast Guides
  url: https://hazelcast.org
  start_page: home::index.adoc
content:
  sources:
    - url: . # home
      branches: HEAD
      start_path: home
    - url: https://github.com/hazelcast-guides/adoc-templates.git
      branches: antora-doc
    - url: https://github.com/hazelcast-guides/hazelcast-embedded-springboot
      branches: master
      start_path: doc
    - url: https://github.com/hazelcast-guides/springboot-hibernate
      branches: master
      start_path: doc
    - url: https://github.com/hazelcast-guides/hibernate-jcache
      branches: master
      start_path: doc
    - url: https://github.com/hazelcast-guides/istio-embedded
      branches: master
      start_path: doc
    - url: https://github.com/hazelcast-guides/caching-micronaut
      branches: master
      start_path: doc
    - url: https://github.com/hazelcast-guides/kubernetes-springboot-embedded
      branches: master
      start_path: doc
    - url: https://github.com/hazelcast-guides/hazelcast-embedded-microprofile
      branches: master
      start_path: doc
    - url: https://github.com/hazelcast-guides/hazelcast-client-quarkus
      branches: master
      start_path: doc
    - url: https://github.com/hazelcast-guides/springboot-webfilter-session-replication
      branches: master
      start_path: doc
    - url: https://github.com/hazelcast-guides/caching-springboot
      branches: master
      start_path: doc
    - url: https://github.com/hazelcast-guides/ecs-embedded
      branches: master
      start_path: doc
    - url: https://github.com/hazelcast-guides/striiim-cdc
      branches: master
      start_path: doc
    - url: https://github.com/hazelcast-guides/caching-springboot-jcache
      branches: master
      start_path: doc
    - url: https://github.com/hazelcast-guides/caching-micronaut-microservices-on-kubernetes
      branches: master
      start_path: doc
    - url: https://github.com/hazelcast-guides/springboot-tomcat-session-replication
      branches: master
      start_path: doc
    - url: https://github.com/hazelcast-guides/springboot-tomcat-session-replication-on-kubernetes
      branches: master
      start_path: doc
ui:
  bundle:
    url: https://github.com/hazelcast-guides/guides-ui/releases/download/v5/ui-bundle.zip
    snapshot: true
